version: '3.4'

services:
  db:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong1_2PAssword
      - MSSQL_PID=Express
  webwork:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB__Type=DockerDB
    ports:
      - "80"
